CREATE DATABASE local;
USE local;

CREATE TABLE users (
  id INT(8) NOT NULL auto_increment,
  username VARCHAR(20) NOT NULL,
  password CHAR(60) NOT NULL,
  deleted TINYINT(1) DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  UNIQUE INDEX username_UNIQUE (username ASC)
);